services:
  - type: web
    name: jkh-backend
    env: node
    buildCommand: cd jkh-system && npm install && npm run build
    startCommand: cd jkh-system && node server.mjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 